name: phoenix-hydra
services:
  phoenix-core:
    image: nginx:alpine
    environment:
      MONETIZATION_MODE: "enterprise"
      AFFILIATE_TRACKING: "enabled"
      MARKETPLACE_INTEGRATION: "aws,cloudflare,huggingface"
    ports:
      - "8080:80"
    volumes:
      - ../../configs/nginx-phoenix-core.html:/usr/share/nginx/html/index.html:ro
    command: >
      sh -c "echo '{\"status\":\"healthy\",\"service\":\"phoenix-hydra\",\"version\":\"v8.7\"}' > /usr/share/nginx/html/health && nginx -g 'daemon off;'"

  nca-toolkit:
    image: nginx:alpine
    environment:
      API_BASE_URL: "https://sea-turtle-app-nlak2.ondigitalocean.app/v1/"
      PHOENIX_INTEGRATION: "true"
    ports:
      - "8081:80"
    volumes:
      - ../../configs/nginx-nca-toolkit.html:/usr/share/nginx/html/index.html:ro
    command: nginx -g 'daemon off;'

  n8n-phoenix:
    image: n8nio/n8n:latest
    environment:
      GENERIC_TIMEZONE: "Europe/Madrid"
      N8N_SECURE_COOKIE: "false"
      N8N_ENCRYPTION_KEY: "phoenix_hydra_n8n_key_2025_secure"
      PHOENIX_WORKFLOWS_ENABLED: "true"
    volumes:
      - n8n_data:/home/node/.n8n:z
    ports:
      - "5678:5678"

  windmill-phoenix:
    image: ghcr.io/windmill-labs/windmill:main
    environment:
      DATABASE_URL: "postgresql://phoenix:hydra2025_secure_password@revenue-db:5432/phoenix_revenue"
      RUST_LOG: "info"
    depends_on:
      - revenue-db
    ports:
      - "8000:8000"

  revenue-db:
    image: postgres:15
    environment:
      POSTGRES_DB: "phoenix_revenue"
      POSTGRES_USER: "phoenix"
      POSTGRES_PASSWORD: "hydra2025_secure_password"
    volumes:
      - revenue_data:/var/lib/postgresql/data:z

volumes:
  n8n_data: {}
  revenue_data: {}
