version: '3.8'

services:
  phoenix-hugger-mega:
    image: pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel
    container_name: phoenix-hugger-mega
    volumes:
      - ../../scripts:/scripts:ro
      - ../../models:/models
      - ../../requirements-models.txt:/requirements.txt:ro
    working_dir: /scripts
    environment:
      - HF_HOME=/root/.cache/huggingface
      - HF_HUB_CACHE=/root/.cache/huggingface/hub
      - TRANSFORMERS_CACHE=/root/.cache/huggingface/transformers
      # Pass the HF_TOKEN from the host environment if it exists
      - HF_TOKEN=${HF_TOKEN}
    command: >
      bash -c "
        echo '🚀 Installing dependencies...' &&
        pip install -r /requirements.txt &&
        echo '✅ Dependencies installed.' &&
        echo '🤖 Executing Phoenix Hugger MEGA script...' &&
        python phoenix_hugger_mega.py --out /models
      "
