# Traefik Dynamic Configuration for Phoenix DemiGod
# Place this file in /etc/traefik/dynamic-conf.toml on manager node

[http]
  # Global HTTP configuration
  [http.middlewares]
    # CORS middleware
    [http.middlewares.cors.headers]
      accessControlAllowMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      accessControlAllowHeaders = ["Content-Type", "Authorization", "X-Requested-With"]
      accessControlAllowOriginList = ["https://phoenix-demigod.local"]
      accessControlMaxAge = 100
      addVaryHeader = true
    
    # Security headers middleware
    [http.middlewares.securityHeaders.headers]
      frameDeny = true
      contentTypeNosniff = true
      browserXssFilter = true
      contentSecurityPolicy = "default-src 'self'; script-src 'self' 'unsafe-inline'"
      referrerPolicy = "strict-origin-when-cross-origin"
      featurePolicy = "camera 'none'; microphone 'none'"
      
    # Basic authentication for admin panels
    [http.middlewares.adminAuth.basicAuth]
      realm = "Phoenix DemiGod Admin Area"
      usersFile = "/etc/traefik/.htpasswd" # Generated with htpasswd
      
    # Rate limiting
    [http.middlewares.rateLimit.rateLimit]
      average = 100
      burst = 50
      
    # IP whitelist for sensitive areas
    [http.middlewares.ipWhitelist.ipWhiteList]
      sourceRange = ["127.0.0.1/32", "192.168.0.0/16", "10.0.0.0/8"]

[tls]
  # Global TLS configuration
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      ]
      sniStrict = true
      
  [[tls.certificates]]
    certFile = "/certificates/phoenix-demigod.crt"
    keyFile = "/certificates/phoenix-demigod.key"
