name: phoenix-hydra
services:
  phoenix-core:
    image: phoenixhydra/core:v8.7
    environment:
      MONETIZATION_MODE: "enterprise"
      AFFILIATE_TRACKING: "enabled"
      MARKETPLACE_INTEGRATION: "aws,cloudflare,huggingface"
    volumes:
      - ./configs:/app/configs:Z
    ports:
      - "8080:8080"
  nca-toolkit:
    image: sea-turtle-app-nlak2:latest
    environment:
      API_BASE_URL: "https://sea-turtle-app-nlak2.ondigitalocean.app/v1/"
      PHOENIX_INTEGRATION: "true"
    ports:
      - "8081:8080"
  n8n-phoenix:
    image: n8nio/n8n:latest
    environment:
      GENERIC_TIMEZONE: "Europe/Madrid"
      # In production, this should be true and a proper encryption key should be set.
      N8N_SECURE_COOKIE: "true"
      # N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
      PHOENIX_WORKFLOWS_ENABLED: "true"
    volumes:
      - n8n_data:/home/node/.n8n:z
    ports:
      - "5678:5678"
  windmill-phoenix:
    image: ghcr.io/windmill-labs/windmill:main
    environment:
      # Use environment variables for secrets. Do not hardcode them.
      # Create a .env file for local development.
      DATABASE_URL: "postgresql://postgres:${WINDMILL_DB_PASSWORD}@revenue-db:5432/windmill"
      RUST_LOG: "info"
    volumes:
      - ./windmill-scripts:/windmill/scripts:Z
    depends_on:
      - revenue-db
    ports:
      - "8000:8000"
  revenue-db:
    image: postgres:15
    environment:
      POSTGRES_DB: "phoenix_revenue"
      POSTGRES_USER: "phoenix"
      # Use environment variables for secrets.
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - revenue_data:/var/lib/postgresql/data:z
volumes:
  n8n_data: {}
  revenue_data: {}
